# Generated by Django 4.0 on 2023-11-22 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='カテゴリ')),
            ],
        ),
        migrations.CreateModel(
            name='Category2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='カテゴリ')),
            ],
        ),
        migrations.CreateModel(
            name='Category3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='カテゴリ')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル名')),
                ('title_image', models.ImageField(upload_to='title_img', verbose_name='タイトル画像')),
                ('mode1', models.CharField(max_length=200, verbose_name='進化形態の名前')),
                ('status1', models.CharField(max_length=200, verbose_name='撃種/戦型/種族')),
                ('ability1', models.CharField(max_length=200, verbose_name='アビリティ')),
                ('gage1', models.CharField(blank=True, max_length=200, null=True, verbose_name='ゲージアビリティ')),
                ('connect_skill1', models.CharField(blank=True, max_length=200, null=True, verbose_name='コネクトスキル')),
                ('connect_joken1', models.CharField(blank=True, max_length=200, null=True, verbose_name='コネクトスキル条件')),
                ('shot_skill1', models.CharField(blank=True, max_length=200, null=True, verbose_name='ショットスキル')),
                ('assist_skill1', models.CharField(blank=True, max_length=200, null=True, verbose_name='アシストスキル')),
                ('strike_shot1', models.CharField(max_length=200, verbose_name='ストライクショット')),
                ('yujou_combo1', models.CharField(max_length=200, verbose_name='友情コンボ')),
                ('fukuyujou_combo1', models.CharField(blank=True, max_length=200, null=True, verbose_name='副友情コンボ')),
                ('luck_skill1', models.CharField(blank=True, max_length=200, null=True, verbose_name='ラックスキル')),
                ('profile1', models.TextField(verbose_name='profile')),
                ('image1', models.ImageField(upload_to='photos', verbose_name='通常イラスト')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='新春/クリスマスイラスト')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='MVイラスト')),
                ('mode2', models.CharField(blank=True, max_length=200, null=True, verbose_name='進化形態の名前')),
                ('status2', models.CharField(blank=True, max_length=200, null=True, verbose_name='撃種/戦型/種族')),
                ('ability2', models.CharField(blank=True, max_length=200, null=True, verbose_name='アビリティ')),
                ('gage2', models.CharField(blank=True, max_length=200, null=True, verbose_name='ゲージアビリティ')),
                ('connect_skill2', models.CharField(blank=True, max_length=200, null=True, verbose_name='コネクトスキル')),
                ('connect_joken2', models.CharField(blank=True, max_length=200, null=True, verbose_name='コネクトスキル条件')),
                ('shot_skill2', models.CharField(blank=True, max_length=200, null=True, verbose_name='ショットスキル')),
                ('assist_skill2', models.CharField(blank=True, max_length=200, null=True, verbose_name='アシストスキル')),
                ('strike_shot2', models.CharField(blank=True, max_length=200, null=True, verbose_name='ストライクショット')),
                ('yujou_combo2', models.CharField(blank=True, max_length=200, null=True, verbose_name='友情コンボ')),
                ('fukuyujou_combo2', models.CharField(blank=True, max_length=200, null=True, verbose_name='副友情コンボ')),
                ('luck_skill2', models.CharField(blank=True, max_length=200, null=True, verbose_name='ラックスキル')),
                ('profile2', models.TextField(blank=True, null=True, verbose_name='プロフィール')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='通常イラスト')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='新春/クリスマスイラスト')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='MVイラスト')),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
                ('category1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kouka2.category1', verbose_name='属性')),
                ('category2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kouka2.category2', verbose_name='進化状態')),
                ('category3', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kouka2.category3', verbose_name='入手方法')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser', verbose_name='ユーザー')),
            ],
        ),
    ]
